### PR TITLE
Sync media query values with Material UI theme - fixes #57

### LINKED ISSUE #57: Broken contact section in tablet
Screen Shot 2020-03-07 at 15 33 05

### PR DESCRIPTION
**Pull request by xMartin**
https://material-ui.com/customization/default-theme/?expand-path=$.breakpoints.values

### CODE REVIEW

File: style/style.js [hunk 1]
```diff
@@ -9,8 +18,8 @@ export const otsTheme = createMuiTheme({
...
 export const mediaquery = {
   mobile: 'max-width: 550px',
-  smallToTablet: 'min-width: 760px',
-  tabletToDesktop: 'min-width: 990px',
-  desktopToBigScreen: 'min-width: 1200px',
-  bigScreenBreakpoint: '1200px',
+  smallToTablet: `min-width: ${customBreakpoints.sm}px`,
+  tabletToDesktop: `min-width: ${customBreakpoints.md}px`,
+  desktopToBigScreen: `min-width: ${customBreakpoints.lg}px`,
+  bigScreenBreakpoint: `${customBreakpoints.lg}px`,
```
Comment (gsambrotta) [inline style/style.js]: we can actually remove this 😅 we never used and i'm not really sure what is the idea behind it since we already have `desktopToBigScreen`

Comment (xMartin) [reply style/style.js]: Yeah, doesn't make much sense...
